name: Dependabot auto-merge

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: dependabot-auto-merge
    runs-on: ubuntu-latest

    if: >
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.repository == 'Astute4185/MHI-AC-Ctrl-ESPHome_ESP-IDF'

    steps:
      - name: Read Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for patch and minor updates
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --squash "$PR_URL"
