esphome:
  name: "airco-ctrl"
  friendly_name: Airco Controller
  min_version: 2025.5.0
  name_add_mac_suffix: false
  platformio_options:
    # Run CPU at 160Mhz to fix mhi_ac_ctrl_core.loop error: -2
    board_build.f_cpu: 160000000L

esp32:
  board: esp32-s3-devkitc-1

# Enable logging
logger:
  level: INFO
  baud_rate: 0

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

external_components:
  - source: github://ginkage/MHI-AC-Ctrl-ESPHome@master
    components: [MhiAcCtrl]

# Version 4.2
MhiAcCtrl:
  # Only 20 (legacy) or 33 (includes 3D auto and vertical vanes) possible.
  # If you encounter mhi_ac_ctrl_core.loop error: -2 errors, change the frame_size to 20
  frame_size: 20
  sck_pin: 21
  miso_pin: 34
  mosi_pin: 48

climate:
  - platform: MhiAcCtrl
    name: "MHI Air Conditioner"

select:
  - platform: MhiAcCtrl
    vertical_vanes:
      name: Fan Control Up Down
    horizontal_vanes:
      name: Fan Control Left Right

switch:
  - platform: MhiAcCtrl
    vanes_3d_auto:
      name: "3D Auto"
sensor:
  - platform: MhiAcCtrl
    outdoor_temperature:
      name: "Outdoor temperature"